services:
  django:
    build: .
    command: gunicorn vkr.wsgi:application --bind 0.0.0.0:8001
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 8001:8001
    depends_on:
      - postgres
    networks:
      - nginx_network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: vkr_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: vkr_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
      - /etc/letsencrypt/live/reform.shspu.ru/fullchain.pem:/etc/letsencrypt/live/reform.shspu.ru/fullchain.pem
      - /etc/letsencrypt/live/reform.shspu.ru/privkey.pem:/etc/letsencrypt/live/reform.shspu.ru/privkey.pem
    depends_on:
      - django
    networks:
      - nginx_network

volumes:
  media_volume:
  pg_data:
  static_volume:

networks:
  nginx_network:
    driver: bridge