# Generated by Django 4.2.16 on 2025-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('technopark', 'Технопарк'), ('deanery', 'Деканат'), ('rectorate', 'Ректорат'), ('uvc', 'Учебно-вычислительный центр (УВЦ)')], max_length=100, unique=True, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
    ]
