# Generated by Django 4.2.16 on 2025-06-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='division',
        ),
    ]
