# Generated by Django 4.2.16 on 2024-11-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0002_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
