# Generated by Django 4.2.16 on 2025-03-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0002_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='fss.divisions', verbose_name='Подразделение'),
        ),
    ]
