# Generated by Django 4.2.16 on 2024-11-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0003_alter_category_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
