# Generated by Django 4.2.16 on 2025-06-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0003_customuser_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='middle_name',
            new_name='patronymic',
        ),
    ]
