# Generated by Django 4.2.16 on 2025-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0004_rename_middle_name_customuser_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='name',
            field=models.CharField(choices=[('technopark', 'Технопарк'), ('deanery', 'Деканат'), ('rectorate', 'Ректорат'), ('uvc', 'Учебно-вычислительный центр (УВЦ)'), ('administration', 'Администрация')], max_length=100, unique=True, verbose_name='Название подразделения'),
        ),
    ]
