# Generated by Django 4.2.16 on 2025-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0005_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('under_review', 'На рассмотрении'), ('approved', 'Подтверждено'), ('preparing', 'Готовится к реализации'), ('in_progress', 'Реализуется'), ('completed', 'Реализовано'), ('rejected', 'Отклонено'), ('archived', 'Архив')], max_length=200, verbose_name='Название статуса'),
        ),
    ]
