# Generated by Django 4.2.16 on 2025-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0005_alter_divisions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
    ]
