# Generated by Django 4.2.16 on 2025-05-11 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fss', '0005_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('under_review', 'На рассмотрении'), ('approved', 'Подтверждено'), ('preparing', 'Готовится к реализации'), ('in_progress', 'Реализуется'), ('completed', 'Реализовано'), ('rejected', 'Отклонено'), ('archived', 'Архив')], max_length=200, verbose_name='Название статуса'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
