# Generated by Django 4.2.16 on 2025-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название подразделения'),
        ),
    ]
