# Generated by Django 4.2.16 on 2025-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fss', '0006_alter_status_name'),
        ('fss', '0006_alter_status_name_notification'),
    ]

    operations = [
    ]
